import { Model, ModelOrigin } from '@/utils/types';
import { chatTemplates } from '@/utils/chat';
import { Platform } from 'react-native';
import { tKey } from '@/i18n';

// Catalog `description`s are translation keys - resolved with i18n.t() in OnDeviceProvider.availableModels().
export const MODEL_LIST_VERSION = 13;
const iosOnlyModels: Model[] = [];
const androidOnlyModels: Model[] = [];

const crossPlatformModels: Model[] = [
  // -------- Gemma --------
  {
    id: 'unsloth/gemma-3-1b-it-GGUF',
    runtime: 'CPU',
    author: 'Google',
    name: 'Gemma-3-1b',
    description: tKey('models.catalog.gemma_3_1b'),
    type: 'Gemma',
    capabilities: ['questionAnswering', 'summarization', 'reasoning'],
    size: 1.07e+9,
    params: 1_000_000_000,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/unsloth/gemma-3-1b-it-GGUF/blob/main/gemma-3-1b-it-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/unsloth/gemma-3-1b-it-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/5dd96eb166059660ed1ee413/WtA3YYitedOr9n02eHfJe.png',
    progress: 0,
    filename: 'gemma-3-1b-it-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.gemma3 },
    chatTemplate: chatTemplates.gemma3,
    defaultCompletionSettings: {
      temperature: 1,
      top_p: 0.95,
      top_k: 64,
      min_p: 0,
    },
    completionSettings: {
      temperature: 1,
      top_p: 0.95,
      top_k: 64,
      min_p: 0,
    },
    defaultStopWords: ['<end_of_turn>'],
    stopWords: ['<end_of_turn>'],
  },

  // -------- Phi --------
  // {
  //   id: 'MaziyarPanahi/Phi-3.5-mini-instruct-GGUF/Phi-3.5-mini-instruct.Q4_K_M.gguf',
  //   runtime: 'CPU',
  //   author: 'MaziyarPanahi',
  //   name: 'Phi-3.5 mini 4k instruct (Q4_K_M)',
  //   type: 'Phi',
  //   capabilities: ['reasoning', 'code', 'math', 'multilingual'],
  //   size: 2393232608,
  //   params: 3821079648,
  //   isDownloaded: false,
  //   downloadUrl:
  //     'https://huggingface.co/MaziyarPanahi/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct.Q4_K_M.gguf',
  //   hfUrl: 'https://huggingface.co/MaziyarPanahi/Phi-3.5-mini-instruct-GGUF',
  //   progress: 0,
  //   filename: 'Phi-3.5-mini-instruct.Q4_K_M.gguf',
  //   isLocal: false,
  //   origin: ModelOrigin.PRESET,
  //   defaultChatTemplate: { ...chatTemplates.phi3 },
  //   chatTemplate: chatTemplates.phi3,
  //   defaultCompletionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.1,
  //   },
  //   completionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.1,
  //   },
  //   defaultStopWords: ['<|end|>'],
  //   stopWords: ['<|end|>'],
  //   hfModelFile: {
  //     rfilename: 'Phi-3.5-mini-instruct.Q4_K_M.gguf',
  //     url: 'https://huggingface.co/MaziyarPanahi/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct.Q4_K_M.gguf',
  //     size: 2393232608,
  //     oid: 'a2b0f35b7504ba395e886fadd5ebc61236b9f5ec',
  //     lfs: {
  //       oid: '3f68916e850b107d8641d18bcd5548f0d66beef9e0a9077fe84ef28943eb7e88',
  //       size: 2393232608,
  //       pointerSize: 135,
  //     },
  //     canFitInStorage: true,
  //   },
  // },
  // -------- Qwen --------
  {
    id: 'unsloth/Qwen3-0.6B-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3-0.6B',
    description: tKey('models.catalog.qwen3_0_6b'),
    type: 'Qwen',
    capabilities: ['text-generation', 'reasoning'],
    size: 639447744,
    params: 600_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q8_0.gguf',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3-0.6B-GGUF',
    progress: 0,
    filename: 'Qwen3-0.6B-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.qwen3 },
    chatTemplate: chatTemplates.qwen3,
    defaultCompletionSettings: {},
    completionSettings: {},
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },
  {
    id: 'unsloth/Qwen3-1.7B-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3-1.7B',
    description: tKey('models.catalog.qwen3_1_7b'),
    type: 'Qwen',
    capabilities: ['text-generation', 'reasoning'],
    size: 1.83e+9,
    params: 1_700_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q8_0.gguf',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3-1.7B-GGUF',
    progress: 0,
    filename: 'Qwen3-1.7B-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.qwen3 },
    chatTemplate: chatTemplates.qwen3,
    defaultCompletionSettings: {
    },
    completionSettings: {
    },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },

  // -------- Llama --------
  {
    id: 'unsloth/Llama-3.2-1B-Instruct-GGUF',
    runtime: 'CPU',
    author: 'Meta',
    name: 'Llama 3.2 1B',
    description: tKey('models.catalog.llama_3_2_1b'),
    type: 'Llama',
    capabilities: ['text-generation'],
    size: 1.32e+9,
    params: 1.24e+9,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/unsloth/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q8_0.gguf',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/646cf8084eefb026fb8fd8bc/oCTqufkdTkjyGodsx1vo1.png',
    hfUrl:
      'https://huggingface.co/unsloth/Llama-3.2-1B-Instruct-GGUF',
    progress: 0,
    filename: 'Llama-3.2-1B-Instruct-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.llama32 },
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
    },
    completionSettings: {
    },
    defaultStopWords: ['<|eot_id|>'],
    stopWords: ['<|eot_id|>'],
    hfModelFile: {
      rfilename: 'llama-3.2-1b-instruct-q8_0.gguf',
      url: 'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-1b-instruct-q8_0.gguf',
      size: 1321079200,
      oid: '4d5402369568f0bd157d8454270821341e833722',
      lfs: {
        oid: 'ba345c83bf5cc679c653b853c46517eea5a34f03ed2205449db77184d9ae62a9',
        size: 1321079200,
        pointerSize: 135,
      },
      canFitInStorage: true,
    },
  },
  // {
  //   id: 'hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF/llama-3.2-1b-instruct-q8_0.gguf',
  //   runtime: 'CPU',
  //   author: 'hugging-quants',
  //   name: 'Llama-3.2-1b-instruct (Q8_0)',
  //   type: 'Llama',
  //   capabilities: ['text-generation'],
  //   size: 1321079200,
  //   params: 1235814432,
  //   isDownloaded: false,
  //   downloadUrl:
  //     'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-1b-instruct-q8_0.gguf',
  //   hfUrl:
  //     'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF',
  //   progress: 0,
  //   filename: 'llama-3.2-1b-instruct-q8_0.gguf',
  //   isLocal: false,
  //   origin: ModelOrigin.PRESET,
  //   defaultChatTemplate: { ...chatTemplates.llama32 },
  //   chatTemplate: chatTemplates.llama32,
  //   defaultCompletionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.5,
  //   },
  //   completionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.5,
  //   },
  //   defaultStopWords: ['<|eot_id|>'],
  //   stopWords: ['<|eot_id|>'],
  //   hfModelFile: {
  //     rfilename: 'llama-3.2-1b-instruct-q8_0.gguf',
  //     url: 'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-1b-instruct-q8_0.gguf',
  //     size: 1321079200,
  //     oid: '4d5402369568f0bd157d8454270821341e833722',
  //     lfs: {
  //       oid: 'ba345c83bf5cc679c653b853c46517eea5a34f03ed2205449db77184d9ae62a9',
  //       size: 1321079200,
  //       pointerSize: 135,
  //     },
  //     canFitInStorage: true,
  //   },
  // },
  // {
  //   id: 'bartowski/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-Q6_K.gguf',
  //   runtime: 'CPU',
  //   author: 'bartowski',
  //   name: 'Llama-3.2-3B-Instruct (Q6_K)',
  //   type: 'Llama',
  //   capabilities: ['text-generation'],
  //   size: 2643853856,
  //   params: 3212749888,
  //   isDownloaded: false,
  //   downloadUrl:
  //     'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q6_K.gguf',
  //   hfUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF',
  //   progress: 0,
  //   filename: 'Llama-3.2-3B-Instruct-Q6_K.gguf',
  //   isLocal: false,
  //   origin: ModelOrigin.PRESET,
  //   defaultChatTemplate: { ...chatTemplates.llama32 },
  //   chatTemplate: chatTemplates.llama32,
  //   defaultCompletionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.5,
  //   },
  //   completionSettings: {
  //     ...defaultCompletionParams,
  //     n_predict: 500,
  //     temperature: 0.5,
  //   },
  //   defaultStopWords: ['<|eot_id|>'],
  //   stopWords: ['<|eot_id|>'],
  //   hfModelFile: {
  //     rfilename: 'Llama-3.2-3B-Instruct-Q6_K.gguf',
  //     url: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q6_K.gguf',
  //     size: 2643853856,
  //     oid: '47d12cf8883aaa6a6cd0b47975cc026980a3af9d',
  //     lfs: {
  //       oid: '1771887c15fc3d327cfee6fd593553b2126e88834bf48eae50e709d3f70dd998',
  //       size: 2643853856,
  //       pointerSize: 135,
  //     },
  //     canFitInStorage: true,
  //   },
  // },
  // ---------------------------------------------------------------------------
  // Modern small models (Sept 2026).
  // NOTE: Gemma 4, Qwen3.5 and Qwen3-VL need the gemma4 / qwen35 / qwen3vl
  // architectures which the bundled llama.rn (>= 0.12.9) runtime knows about.
  // Quants were picked to stay phone-sized while keeping quality: Q8_0 for
  // sub-1B models, Q6_K / UD-Q4_K_XL around 2B, Q4_K_M for 3B, and Google's
  // QAT "mobile" Q2_K_XL builds for Gemma 4 (trained for that quant).
  // ---------------------------------------------------------------------------

  // -------- Qwen 3.5 --------
  {
    id: 'unsloth/Qwen3.5-0.8B-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3.5 0.8B',
    description: tKey('models.catalog.qwen3_5_0_8b'),
    type: 'Qwen',
    capabilities: ['text-generation', 'tool-use', 'multilingual', 'vision'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 204987232,
    },
    size: 811843840,
    params: 800_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    progress: 0,
    filename: 'Qwen3.5-0.8B-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    // Thinking is disabled: at 0.8B the reasoning trace burns tokens (and time) without improving the answer.
    defaultCompletionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0, enable_thinking: false },
    completionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0, enable_thinking: false },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },
  {
    id: 'unsloth/Qwen3.5-2B-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3.5 2B',
    description: tKey('models.catalog.qwen3_5_2b'),
    type: 'Qwen',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'multilingual', 'vision'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 668227264,
    },
    size: 2158137344,
    params: 2_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    progress: 0,
    filename: 'Qwen3.5-2B-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    completionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },
  {
    id: 'unsloth/Qwen3.5-4B-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3.5 4B',
    description: tKey('models.catalog.qwen3_5_4b'),
    type: 'Qwen',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'multilingual', 'vision'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 672423616,
    },
    size: 3791650816,
    params: 4_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q6_K.gguf',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    progress: 0,
    filename: 'Qwen3.5-4B-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    completionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },

  // -------- Qwen3-VL --------
  {
    id: 'unsloth/Qwen3-VL-2B-Instruct-GGUF',
    runtime: 'CPU',
    author: 'Qwen',
    name: 'Qwen3-VL 2B Instruct',
    description: tKey('models.catalog.qwen3_vl_2b_instruct'),
    type: 'Qwen',
    capabilities: ['text-generation', 'vision', 'multilingual'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3-VL-2B-Instruct-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 819395232,
    },
    size: 1129709248,
    params: 2_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3-VL-2B-Instruct-GGUF/resolve/main/Qwen3-VL-2B-Instruct-UD-Q4_K_XL.gguf',
    hfUrl: 'https://huggingface.co/unsloth/Qwen3-VL-2B-Instruct-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png',
    progress: 0,
    filename: 'Qwen3-VL-2B-Instruct-UD-Q4_K_XL.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    completionSettings: { temperature: 0.7, top_p: 0.8, top_k: 20, min_p: 0 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },

  // -------- IBM Granite --------
  {
    id: 'unsloth/granite-3.3-2b-instruct-GGUF',
    runtime: 'CPU',
    author: 'IBM Research',
    name: 'Granite 3.3 2B Instruct',
    description: tKey('models.catalog.granite_3_3_2b_instruct'),
    type: 'Granite',
    capabilities: ['text-generation', 'summarization', 'tool-use', 'questionAnswering'],
    size: 1570731264,
    params: 2_500_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/granite-3.3-2b-instruct-GGUF/resolve/main/granite-3.3-2b-instruct-UD-Q4_K_XL.gguf',
    hfUrl: 'https://huggingface.co/unsloth/granite-3.3-2b-instruct-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/639bcaa2445b133a4e942436/CEW-OjXkRkDNmTxSu8Egh.png',
    progress: 0,
    filename: 'granite-3.3-2b-instruct-UD-Q4_K_XL.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.custom },
    chatTemplate: { ...chatTemplates.custom },
    defaultCompletionSettings: { temperature: 0.7 },
    completionSettings: { temperature: 0.7 },
    defaultStopWords: ['<|end_of_text|>'],
    stopWords: ['<|end_of_text|>'],
  },
  {
    id: 'ibm-granite/granite-4.2-3b-GGUF',
    runtime: 'CPU',
    author: 'IBM Research',
    name: 'Granite 4.2 3B',
    description: tKey('models.catalog.granite_4_2_3b'),
    type: 'Granite',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'questionAnswering'],
    size: 2244011552,
    params: 3_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/ibm-granite/granite-4.2-3b-GGUF/resolve/main/granite-4.2-3b-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/ibm-granite/granite-4.2-3b-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/639bcaa2445b133a4e942436/CEW-OjXkRkDNmTxSu8Egh.png',
    progress: 0,
    filename: 'granite-4.2-3b-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.7 },
    completionSettings: { temperature: 0.7 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },

  // -------- Liquid AI --------
  // Official LiquidAI GGUFs. LFM2.5 is a hybrid conv/attention architecture built for
  // CPU inference, so it is fast on phones. Liquid recommends temperature 0.1 / top_k 50.
  {
    id: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF',
    runtime: 'CPU',
    author: 'Liquid AI',
    name: 'LFM2.5 1.2B Instruct',
    description: tKey('models.catalog.lfm2_5_1_2b_instruct'),
    type: 'LFM',
    capabilities: ['text-generation', 'tool-use', 'multilingual', 'questionAnswering'],
    size: 1246253888,
    params: 1_170_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF/resolve/main/LFM2.5-1.2B-Instruct-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/61b8e2ba285851687028d395/EsTgVtnM2IqVRKgPdfqcB.png',
    progress: 0,
    filename: 'LFM2.5-1.2B-Instruct-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.1, top_k: 50 },
    completionSettings: { temperature: 0.1, top_k: 50 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },
  {
    id: 'LiquidAI/LFM2.5-2.6B-GGUF',
    runtime: 'CPU',
    author: 'Liquid AI',
    name: 'LFM2.5 2.6B',
    description: tKey('models.catalog.lfm2_5_2_6b'),
    type: 'LFM',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'multilingual'],
    size: 1939744768,
    params: 2_700_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B-GGUF/resolve/main/LFM2.5-2.6B-Q5_K_M.gguf',
    hfUrl: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/61b8e2ba285851687028d395/EsTgVtnM2IqVRKgPdfqcB.png',
    progress: 0,
    filename: 'LFM2.5-2.6B-Q5_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.chatML },
    chatTemplate: { ...chatTemplates.chatML },
    defaultCompletionSettings: { temperature: 0.1, top_k: 50 },
    completionSettings: { temperature: 0.1, top_k: 50 },
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
  },

  // -------- Gemma 4 --------
  // Google's QAT "mobile" builds. Gemma 4 uses per-layer embeddings so the file
  // is larger than the effective parameter count suggests.
  {
    id: 'unsloth/gemma-4-E2B-it-qat-mobile-GGUF',
    runtime: 'CPU',
    author: 'Google',
    name: 'Gemma 4 E2B',
    description: tKey('models.catalog.gemma_4_e2b'),
    type: 'Gemma',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'multilingual', 'vision'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E2B-it-qat-mobile-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 985654080,
    },
    size: 2186186784,
    params: 2_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E2B-it-qat-mobile-GGUF/resolve/main/gemma-4-E2B-it-qat-UD-Q2_K_XL.gguf',
    hfUrl: 'https://huggingface.co/unsloth/gemma-4-E2B-it-qat-mobile-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/5dd96eb166059660ed1ee413/WtA3YYitedOr9n02eHfJe.png',
    progress: 0,
    filename: 'gemma-4-E2B-it-qat-UD-Q2_K_XL.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.custom },
    chatTemplate: { ...chatTemplates.custom },
    defaultCompletionSettings: { temperature: 1, top_p: 0.95, top_k: 64, min_p: 0 },
    completionSettings: { temperature: 1, top_p: 0.95, top_k: 64, min_p: 0 },
    defaultStopWords: ['<turn|>'],
    stopWords: ['<turn|>'],
  },
  {
    id: 'unsloth/gemma-4-E4B-it-qat-mobile-GGUF',
    runtime: 'CPU',
    author: 'Google',
    name: 'Gemma 4 E4B',
    description: tKey('models.catalog.gemma_4_e4b'),
    type: 'Gemma',
    capabilities: ['text-generation', 'reasoning', 'tool-use', 'multilingual', 'vision'],
    mmproj: {
      downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E4B-it-qat-mobile-GGUF/resolve/main/mmproj-F16.gguf',
      filename: 'mmproj-F16.gguf',
      size: 990372672,
    },
    size: 3219532192,
    params: 4_000_000_000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E4B-it-qat-mobile-GGUF/resolve/main/gemma-4-E4B-it-qat-UD-Q2_K_XL.gguf',
    hfUrl: 'https://huggingface.co/unsloth/gemma-4-E4B-it-qat-mobile-GGUF',
    imageUrl: 'https://cdn-avatars.huggingface.co/v1/production/uploads/5dd96eb166059660ed1ee413/WtA3YYitedOr9n02eHfJe.png',
    progress: 0,
    filename: 'gemma-4-E4B-it-qat-UD-Q2_K_XL.gguf',
    isLocal: false,
    origin: ModelOrigin.HF,
    defaultChatTemplate: { ...chatTemplates.custom },
    chatTemplate: { ...chatTemplates.custom },
    defaultCompletionSettings: { temperature: 1, top_p: 0.95, top_k: 64, min_p: 0 },
    completionSettings: { temperature: 1, top_p: 0.95, top_k: 64, min_p: 0 },
    defaultStopWords: ['<turn|>'],
    stopWords: ['<turn|>'],
  },
];

export const defaultModels =
  Platform.OS === 'android'
    ? [...androidOnlyModels, ...crossPlatformModels]
    : [...iosOnlyModels, ...crossPlatformModels];
