// `yarn translations:normalize`
// Brings every language in src/locales/languages.json in line with the English dictionary:
// - creates missing language files
// - adds new English keys as null (shown in English until translated), drops keys English no longer has
// - expands plural keys to each language's own CLDR categories (eg. Russian needs _one/_few/_many/_other)
// - keeps key order identical to English so diffs stay readable
// - regenerates src/locales/resources.ts
import fs from "fs";
import path from "path";
import {
  LANGUAGES,
  LOCALES_DIR,
  PRIMARY,
  expectedKeys,
  flatten,
  log,
  readLocale,
  unflatten,
  writeLocale,
} from "./lib.mjs";

const flatEn = flatten(readLocale(PRIMARY));

for (const { code } of LANGUAGES) {
  if (code === PRIMARY) continue;
  const existing = flatten(readLocale(code) ?? {});
  const next = {};
  let added = 0;
  for (const key of expectedKeys(code, flatEn).keys()) {
    const value = existing[key];
    if (typeof value === "string" && value !== "") next[key] = value;
    else {
      next[key] = null;
      if (!(key in existing)) added++;
    }
  }
  const removed = Object.keys(existing).filter(key => !(key in next)).length;
  writeLocale(code, unflatten(next));
  if (added || removed) log(`${code}: +${added} new, -${removed} removed`);
}

// Stable import names for codes like pt-BR / zh-TW.
const identifier = code => code.replace(/-/g, "_");
const codes = LANGUAGES.map(lang => lang.code).filter(code => readLocale(code));
const resources = `// GENERATED by \`yarn translations:normalize\` - do not edit by hand.
// Lists every language in languages.json that has a locales/<code>/common.json file.
${codes.map(code => `import ${identifier(code)} from "./${code}/common.json";`).join("\n")}

export const defaultNS = "common";
export const resources = {
${codes.map(code => `  ${code.includes("-") ? `"${code}"` : code}: { common: ${identifier(code)} },`).join("\n")}
} as const;
`;
fs.writeFileSync(path.join(LOCALES_DIR, "resources.ts"), resources);
log(`Normalized ${codes.length - 1} language file(s) against English and regenerated resources.ts`);
