// GENERATED by `yarn translations:normalize` - do not edit by hand.
// Lists every language in languages.json that has a locales/<code>/common.json file.
import en from "./en/common.json";
import de from "./de/common.json";
import es from "./es/common.json";
import fr from "./fr/common.json";
import hi from "./hi/common.json";
import id from "./id/common.json";
import it from "./it/common.json";
import ja from "./ja/common.json";
import ko from "./ko/common.json";
import nl from "./nl/common.json";
import pl from "./pl/common.json";
import pt_BR from "./pt-BR/common.json";
import ru from "./ru/common.json";
import tr from "./tr/common.json";
import vi from "./vi/common.json";
import zh from "./zh/common.json";
import zh_TW from "./zh-TW/common.json";

export const defaultNS = "common";
export const resources = {
  en: { common: en },
  de: { common: de },
  es: { common: es },
  fr: { common: fr },
  hi: { common: hi },
  id: { common: id },
  it: { common: it },
  ja: { common: ja },
  ko: { common: ko },
  nl: { common: nl },
  pl: { common: pl },
  "pt-BR": { common: pt_BR },
  ru: { common: ru },
  tr: { common: tr },
  vi: { common: vi },
  zh: { common: zh },
  "zh-TW": { common: zh_TW },
} as const;
