import { field, text } from '@nozbe/watermelondb/decorators';
import { database } from '@/database';
import { Q, Model } from '@nozbe/watermelondb';
import { generateUUID } from '@/utils/constants';

export type MemoryScope = 'global' | 'workspace';

export type MemoryType = {
  uuid: string;
  scope: MemoryScope;
  /** Set for `workspace` scoped memories only */
  workspaceSlug: string | null;
  content: string;
  /** Embedding of `content` from the on-device embedder, or `null` when it has not been embedded yet */
  embedding: number[] | null;
  createdAt: number;
  updatedAt: number;
};

export type MemoryDBType = Model & {
  uuid: string;
  scope: MemoryScope;
  workspaceSlug: string | null;
  content: string;
  embedding: string | null;
  createdAt: number;
  updatedAt: number;
};

/**
 * A user-authored memory: a short fact the model should know, injected into prompts by
 * `MemoryManager` (utils/Memories). The user writes and scopes every memory themselves - nothing
 * here is generated by a model. Rows are plain SQLite; the embedding is a JSON float array so
 * the small set of memories can be searched in JS without touching the document vector store.
 */
export default class Memory extends Model {
  static table = 'memories';

  /** Keeps every memory a single dense sentence or two so the injected block stays cheap. */
  static maxContentLength = 300;
  static minContentLength = 2;

  @text('uuid') uuid!: string;
  @text('scope') scope!: MemoryScope;
  @text('workspace_slug') workspaceSlug!: string | null;
  @text('content') content!: string;
  @text('embedding') embedding!: string | null;
  @field('created_at') createdAt!: number;
  @field('updated_at') updatedAt!: number;

  static log(message: any, ...args: any[]) {
    console.log(`\x1b[32m[db:Memory]\x1b[0m`, message, ...args);
  }

  static validateContent(value: unknown): { valid: boolean; error: string; content: string } {
    const content = typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : '';
    let error = '';
    if (typeof value !== 'string') error = 'Memory must be text';
    else if (content.length < Memory.minContentLength) error = 'Memory is too short';
    else if (content.length > Memory.maxContentLength) error = `Memory must be ${Memory.maxContentLength} characters or fewer`;
    return { valid: !error, error, content };
  }

  static parseEmbedding(raw: unknown): number[] | null {
    if (!raw) return null;
    try {
      const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw;
      if (!Array.isArray(parsed) || parsed.length === 0) return null;
      return parsed.map(Number);
    } catch {
      return null;
    }
  }

  static toMemoryObject(data: any): MemoryType {
    const { uuid, scope, workspaceSlug, content, embedding, createdAt, updatedAt } = data;
    return {
      uuid,
      scope,
      workspaceSlug: scope === 'workspace' ? (workspaceSlug ?? null) : null,
      content,
      embedding: Memory.parseEmbedding(embedding),
      createdAt,
      updatedAt,
    };
  }

  /** Watermelon model instances for a set of where clauses (all rows when empty). */
  static async get(where: { field: string, value: any }[] = []): Promise<MemoryDBType[]> {
    const rows = await database.get(Memory.table).query(
      where.map((clause) => Q.where(clause.field, clause.value))
    ).fetch();
    return rows as MemoryDBType[];
  }

  static async find(where: { field: string, value: any }[] = []): Promise<MemoryType[]> {
    const rows = await this.get(where);
    return rows
      .map((row) => this.toMemoryObject(row))
      .sort((a, b) => a.createdAt - b.createdAt);
  }

  static async findByUuid(uuid: string): Promise<MemoryType | null> {
    const rows = await this.get([{ field: 'uuid', value: uuid }]);
    return rows.length ? this.toMemoryObject(rows[0]) : null;
  }

  /** Every memory that applies to a workspace: all global memories plus the ones scoped to `workspaceSlug`. */
  static async forWorkspace(workspaceSlug: string | null): Promise<{ global: MemoryType[]; workspace: MemoryType[] }> {
    const [global, workspace] = await Promise.all([
      this.find([{ field: 'scope', value: 'global' }]),
      workspaceSlug
        ? this.find([{ field: 'scope', value: 'workspace' }, { field: 'workspace_slug', value: workspaceSlug }])
        : Promise.resolve([] as MemoryType[]),
    ]);
    return { global, workspace };
  }

  static async count(): Promise<number> {
    return database.get(Memory.table).query().fetchCount();
  }

  static async create({
    content,
    scope,
    workspaceSlug = null,
  }: {
    content: string;
    scope: MemoryScope;
    workspaceSlug?: string | null;
  }): Promise<MemoryType> {
    const validation = Memory.validateContent(content);
    if (!validation.valid) throw new Error(validation.error);
    if (scope !== 'global' && scope !== 'workspace') throw new Error('Invalid memory scope');
    if (scope === 'workspace' && !workspaceSlug) throw new Error('Workspace memories need a workspace');

    let created: any;
    await database.write(async () => {
      created = await database.get(Memory.table).create((memory: any) => {
        memory.uuid = generateUUID();
        memory.scope = scope;
        memory.workspaceSlug = scope === 'workspace' ? workspaceSlug : null;
        memory.content = validation.content;
        memory.embedding = null;
        memory.createdAt = Date.now();
        memory.updatedAt = Date.now();
      });
    });
    const memory = this.toMemoryObject(created);
    this.log(`created ${memory.scope} memory ${memory.uuid}${memory.workspaceSlug ? ` (${memory.workspaceSlug})` : ''}`);
    return memory;
  }

  /** Rewrites the text of a memory. The stale embedding is cleared so it is re-embedded before its next use. */
  static async updateContent(uuid: string, content: string): Promise<MemoryType | null> {
    const validation = Memory.validateContent(content);
    if (!validation.valid) throw new Error(validation.error);

    const rows = await this.get([{ field: 'uuid', value: uuid }]);
    if (!rows.length) return null;

    let updated: any = rows[0];
    await database.write(async () => {
      updated = await rows[0].update((memory: any) => {
        memory.content = validation.content;
        memory.embedding = null;
        memory.updatedAt = Date.now();
      });
    });
    this.log(`updated memory ${uuid}`);
    return this.toMemoryObject(updated);
  }

  static async setEmbedding(uuid: string, embedding: number[] | null): Promise<boolean> {
    const rows = await this.get([{ field: 'uuid', value: uuid }]);
    if (!rows.length) return false;
    await database.write(async () => {
      await rows[0].update((memory: any) => {
        memory.embedding = embedding && embedding.length ? JSON.stringify(embedding) : null;
      });
    });
    return true;
  }

  static async delete(where: { field: string, value: any }[] = []): Promise<number> {
    try {
      if (!where.length) return 0;
      const rows = await this.get(where);
      if (!rows.length) return 0;
      await database.write(async () => {
        await database.batch(rows.map((row) => row.prepareDestroyPermanently()));
      });
      this.log(`deleted ${rows.length} memories`, where);
      return rows.length;
    } catch (error) {
      console.error('Error deleting memories:', error);
      return 0;
    }
  }

  static async deleteByUuid(uuid: string): Promise<boolean> {
    return (await this.delete([{ field: 'uuid', value: uuid }])) > 0;
  }

  /** Prunes the workspace-scoped memories of the given workspaces. Called when a workspace is deleted. */
  static async deleteForWorkspaces(workspaceSlugs: string[]): Promise<number> {
    if (!workspaceSlugs.length) return 0;
    return this.delete([{ field: 'workspace_slug', value: Q.oneOf(workspaceSlugs) }]);
  }

  static async deleteAll(): Promise<boolean> {
    const rows = await this.get();
    if (!rows.length) return true;
    await database.write(async () => {
      this.log(`deleting ${rows.length} memories`);
      await database.batch(rows.map((row) => row.prepareDestroyPermanently()));
    });
    return true;
  }
}
